name: "pre-release"

on:
  push:
    branches:
      - "master"


jobs:
  build:
    name: "Pre Release"
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - name: "Zip folder"
      run: |
         chmod +x ./ZipLibs.sh
          ./ZipLibs.sh
      shell: bash
  pre-release:
    runs-on: "ubuntu-latest"
    steps:
      # ...
      - name: "Release"
        run: |
          echo "Iniciando..."
          
      
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            LICENSE.txt
            *.zip
