name: "Release"

on:
  push:
    branches:
      - "master"


jobs:
  build:
    name: "Create Libs.zip"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: "Zip folder"
        run: |
           chmod +x ./ZipLibs.sh
            ./ZipLibs.sh
        shell: bash
        
      - name: "Release"
        run: |
          echo "Iniciando..."
          
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          files: |
            LICENSE.txt
            ./Libs/*.jar
     
